### ISSUE TITLE
I2S stream must be initialized before pcm.begin()

### ISSUE THREAD

**Issue by Maigre** [tommag/PCM51xx_Arduino#1]
On ESP32, if no I2S stream had been instantiated before calling pcm.begin()
it fails to start: at the end of pcm.begin() we check the PowerState which sticks to 0 
if we did not start I2S before. If I2S is started after, it should still works, since PowerState goes
from 0 to 5, but pcm.begin() did return false, which is confusing.

-> don't test PowerState when pcm.begin() returns ?
-> enforce I2S started before pcm.begin() ? (at least in documentation... ?)

**Comment by tommag** [comment]
As stated in the README files and in the examples, please start the I2S source before configuring the clock.
